---
- name: copy project files to remote host
  copy:
    src: '{{role_path}}/files/'
    dest: '{{project_dir}}/athena'

- name: remove existing cluster
  docker_compose:
    project_src: '{{project_dir}}/athena'
    state: absent

- name: create new cluster
  docker_compose:
    project_src: '{{project_dir}}/athena'
    state: present