version: "3.3"
services:
  zoo1:
    image: zookeeper:3.6.1
    restart: on-failure
    hostname: zoo1
    ports:
      - 2181:2181
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - master_net
  zoo2:
    image: zookeeper:3.6.1
    restart: on-failure
    hostname: zoo2
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - master_net
  zoo3:
    image: zookeeper:3.6.1
    restart: on-failure
    hostname: zoo3
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      - master_net
networks:
  master_net:
    external: true
    driver: overlay